theme = "gruvbox_dark_soft"

[editor]
auto-completion = true
bufferline = "always"
line-number = "relative"
mouse = true
rulers = [100, 120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.gutters.line-numbers]
min-width = 6

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.normal.space]
c = "toggle_comments"
m = ":format"
