theme = "gruvbox_hash"

[editor]
line-number = "relative"
bufferline = "always"
rulers = [100, 120]
mouse = true
auto-save = { after-delay.enable = true }
text-width = 100
scrolloff = 5
shell = ["fish", "-c"]

[editor.clipboard-provider]
yank-command = "clip-copy"
paste-command = "clip-paste"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.gutters.line-numbers]
min-width = 6

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.search]
smart-case = true

[keys.normal.space]
c = "toggle_comments"
m = ":format"
