# Starship prompt config
# Docs: https://starship.rs/config/

add_newline = false

[git_branch]
format = "[$branch(:$remote_branch)]($style) "
symbol = ""

[git_status]
format = "($all_status$ahead_behind)"
stashed = "\\$${count} "
conflicted = "=${count} "
untracked = "?${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇡${ahead_count} ⇣${behind_count} "
