import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[font]
normal = { family = "MesloLGS Nerd Font Mono" }
size = 19.5

[window]
decorations = "None"
# dimensions = { columns = 100, lines = 30 }
option_as_alt = "Both"
padding = { x = 0, y = 0 }
position = { x = 60, y = 120 }
startup_mode = "Windowed"
