import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]
live_config_reload = true

[env]
TERM = "alacritty-direct"

[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[font]
normal = { family = "Hack Nerd Font Mono" }
size = 23.0

[window]
decorations = "buttonless"
dimensions = { columns = 100, lines = 30 }
option_as_alt = "Both"
padding = { x = 5, y = 5 }
position = { x = 15, y = 50 }
startup_mode = "windowed"
